### ISSUE TITLE
Introduce proper data update procedure

### ISSUE THREAD

**Issue by alexwh** [fizzypop109/fizzypop109.github.io#8]
https://github.com/fizzypop109/fizzypop109.github.io/commit/b40f05e00c192d85aeb165c8b214a905278d37ef just broke the site for me, as my localstorage object was referencing the old names, resulting in a null document.getElementById call on these two lines, halting execution for the rest of the loads: 

https://github.com/fizzypop109/fizzypop109.github.io/blob/dbb924d59925a7109da9e48b4bc84d1f31205da9/pt.js#L436-L445

Perhaps you could use some sort of mapping table from old to new names, or just make renames visual in future, keeping the backend variable name always the same? You could also just catch and throw this away, but that will introduce data loss for those who have marked something that's been renamed as caught/donated.

**Comment by fizzypop109** [comment]
Thanks for pointing out the code issue. I've pushed an update which will stop this error from occurring, but essentially if an item is renamed, for now it will be reset in the list, as the data name directly coincides with the id of the checkbox, so it will need to be remarked as donated.

Not too sure how to approach being able to change the name in the display, but then having it remain the same in the back-end, though that definitely sounds like the optimal option..!

**Comment by alexwh** [comment]
I think if this is the solution you're using for now, there should be at least some sort of warning that some data was just munched (and which data). Since this is primarily used as an archive of donations, if the site can't keep integrity of data it's not very useful.
