### ISSUE TITLE
Incorrect hours for one bug

### ISSUE THREAD

**Issue by plaperdr** [fizzypop109/fizzypop109.github.io#9]
Hi! Thanks a lot for your progress tracker that works very well!
I have noticed there seems to be an incorrect time listed for the "Great Purple Emperor". It is written 4am to 7am where it should be 4am to 7pm! I haven't been able to verify that myself though.

**Comment by SeesamuCaek** [comment]
This is true, I caught one today at 5:30 pm

**Comment by fizzypop109** [comment]
This has been updated, thank you :)
